In [5]:
import pandas as pd 

df = pd.read_excel("imoveis_aquisicoes_brasil.xlsx")

df

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [6]:
# nesse caso o len mostra a quatidade de linhas 

print(len(df))

1500

In [7]:
# aqui o len já mostra a quantidade de colunas 
print(len(df.columns))

8

In [8]:
# b) Quantas colunas numéricas o dataset possui?
# lembrando que o dataset é o conjunto de dados que estão na minha tabela  e o projeto é a pasta
# que tem essa tabela mas também tem o notebook (.ipynb) com o código, o ambiente virtual Venv, 
# as bibliotecas  e etc...

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   logradouro       1500 non-null   str
 1   tipo_logradouro  1500 non-null   str
 2   bairro           1500 non-null   str
 3   cidade           1500 non-null   str
 4   cep              1500 non-null   int64
 5   tipo             1500 non-null   str
 6   valor            1500 non-null   float64
 7   data_aquisicao   1500 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 93.9 KB

In [9]:
# b) Quantas colunas numéricas o dataset possui?
# já nesse caso  ele mostra já calculado a quantidade de colunas por tipo. 
# df.dtypes = lista o tipo de cada coluna 
# .value_counts()  conta quantas colunas tem por esses tipos que eu listei no df.dtypes

df.dtypes.value_counts()

str               5
int64             1
float64           1
datetime64[us]    1
Name: count, dtype: int64

In [10]:
# d) Escreva o endereço completo do imóvel com o menor valor 
# esse sort_values  ordena os valores do menor para o maior 

df.sort_values("valor")

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
...,...,...,...,...,...,...,...,...
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17

In [11]:
# d) Escreva o endereço completo do imóvel com o maior valor 
# esse sort_values (coluna , ascending=False) ordena os valores do maior para o menor. 

df.sort_values("valor" , ascending=False)

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
...,...,...,...,...,...,...,...,...
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10

In [12]:
# Calcule a soma dos valores de todos os imóveis da tabela
# quando vou acessar uma coluna é sempre [] e quando vou chamar uma função  é sempre  ()
# [] = pegar/filtrar dados
# () = executar algo (função/método)

df['valor'].sum()

np.float64(1316455000.0)

In [13]:
# Calcule a soma dos valores de todos os imóveis da tabela
soma = df["valor"].sum()

print(f"A soma dos valores dos imóveis é de R$ {soma}")

A soma dos valores dos imóveis é de R$ 1316455000.0

In [14]:
# Calcule a soma dos valores de todos os imóveis da tabela
# aqui usei o print de um jeito diferente , somei string com a variável soma  
# mas o que está dentro dessa variável tem que ser string também , por  isso usei o str

soma = str(df['valor'].sum())
print("A soma dos valores dos imóveis é de R$ " + soma)

A soma dos valores dos imóveis é de R$ 1316455000.0

In [15]:
# Calcule a média dos valores de todos os imóveis da tabela

df['valor'].mean()

np.float64(877636.6666666666)

In [16]:
# Calcule a média dos valores de todos os imóveis da tabela

media= df['valor'].mean()

print(f"A média dos valores dos imóveis é de R$ {media}")

A média dos valores dos imóveis é de R$ 877636.6666666666

In [17]:
# Calcule a mediana dos valores de todos os imóveis da tabela

df['valor'].median()

np.float64(712500.0)

In [18]:
# Calcule a mediana dos valores de todos os imóveis da tabela

mediana = df['valor'].median()

print(f"A mediana dos valores dos imóveis é de R$ {mediana}")

A mediana dos valores dos imóveis é de R$ 712500.0

In [19]:
# Calcule o desvio padrão dos valores de todos os imóveis da tabela


df['valor'].std()

np.float64(646676.0007057745)

In [20]:
# Calcule o desvio padrão dos valores de todos os imóveis da tabela

desvio_padrao = df["valor"].std()

print(f"O desvio padrão dos imóveis é de {desvio_padrao}")

O desvio padrão dos imóveis é de 646676.0007057745

In [21]:
# Exiba apenas os imóveis da cidade "Curitiba"
# desse jeito eu não criei variável. Mas no próximo vou criá-la 
 
df[df["cidade"] == "Curitiba"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [22]:
# Exiba apenas os imóveis da cidade "Curitiba"

df_Curitiba = df[df["cidade"] == "Curitiba"]


df_Curitiba

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [23]:
# Nesse caso , ele puxou Niteroi porque eu usei o DF original , se eu tivesse usado o df_Curitiba   == Niteroi não teria vindo nada  

df_Curitiba = df[df["cidade"] == "Niteroi"]

df_Curitiba

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
597,dos Jacarandas,Rua,Alto da Baia,Niteroi,24318258,Cobertura,1650000.0,2016-01-27
598,Monte Claro Central,Largo,Alto da Baia,Niteroi,24217002,Casa,508000.0,2016-06-13
599,dos Jacarandas Sul,Praca,Alto da Baia,Niteroi,24372192,Terreno,1505000.0,2016-12-29
600,Nova Aurora,Rua,Alto da Baia,Niteroi,24387600,Kitnet,271000.0,2019-05-14
601,Domingos Arantes,Rua,Alto da Baia,Niteroi,24369855,Terreno,950000.0,2019-12-21
602,das Violetas,Rua,Alto da Baia,Niteroi,24346475,Sala Comercial,997500.0,2021-06-03
603,Sol Nascente,Rua,Alto da Baia,Niteroi,24176083,Apartamento,817500.0,2024-07-05
604,Alto do Cedro,Rua,Campo Oceano Verde,Niteroi,24286061,Apartamento,702500.0,2016-12-07
605,das Orquideas,Travessa,Campo Oceano Verde,Niteroi,24391369,Apartamento,453000.0,2017-03-25
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
607,Professor Almeida,Avenida,Jardim Icarai Novo,Niteroi,24016406,Apartamento,905000.0,2015-06-26
608,das Violetas,Travessa,Jardim Icarai Novo,Niteroi,24110292,Apartamento,418000.0,2015-09-04
609,Raul Peixoto,Alameda,Jardim Icarai Novo,Niteroi,24305192,Casa,1362500.0,2018-11-14
610,Paineiras,Avenida,Jardim Icarai Novo,Niteroi,24342897,Apartamento,1237500.0,2026-04-25
611,Canario Branco,Avenida,Parque Fonseca Novo,Niteroi,24228340,Casa,792500.0,2015-11-22
612,Antonio Loureiro,Alameda,Parque Fonseca Novo,Niteroi,24112786,Terreno,875000.0,2016-12-09
613,Engenheiro Tavares,Alameda,Parque Fonseca Novo,Niteroi,24389911,Apartamento,617500.0,2021-07-25
614,Comendador Prado,Avenida,Parque Fonseca Novo,Niteroi,24304314,Sobrado,1372500.0,2023-07-18
615,Horizonte Azul,Avenida,Parque Fonseca Novo,Niteroi,24180462,Loja,1287500.0,2024-08-17
616,Sol Nascente Oeste,Rua,Praia das Conchas,Niteroi,24135666,Casa,705000.0,2014-06-08
617,Clara Nogueira Leste,Rua,Praia das Conchas,Niteroi,24309569,Apartamento,416000.0,2016-06-12
618,Laura Amaral,Avenida,Praia das Conchas,Niteroi,24243851,Apartamento,365000.0,2017-11-27
619,Sao Vicente,Rua,Praia das Conchas,Niteroi,24283038,Cobertura,2895000.0,2021-02-01
620,Vista Alegre,Rua,Praia das Conchas,Niteroi,24051243,Apartamento,660000.0,2021-04-14
621,Augusto Ferraz,Rodovia,Praia das Conchas,Niteroi,24220807,Casa,712500.0,2021-10-27
622,das Cerejeiras,Rua,Praia das Conchas,Niteroi,24105991,Terreno,1520000.0,2024-12-21
623,Flor do Campo Norte,Rua,Residencial Pendotiba Sul,Niteroi,24215230,Apartamento,339000.0,2014-06-12
624,Veredas do Lago,Rua,Residencial Pendotiba Sul,Niteroi,24224208,Apartamento,369000.0,2014-08-10
625,Serra Bonita,Alameda,Residencial Pendotiba Sul,Niteroi,24029352,Chacara,962500.0,2018-10-28
626,Irene Barbosa,Rua,Residencial Pendotiba Sul,Niteroi,24343684,Apartamento,800000.0,2018-12-15
627,das Figueiras Leste,Avenida,Residencial Pendotiba Sul,Niteroi,24266997,Apartamento,492000.0,2022-03-10
628,Vale Verde,Estrada,Vila Barreto Clara,Niteroi,24315298,Sobrado,612500.0,2014-03-19
629,Raul Peixoto,Rua,Vila Barreto Clara,Niteroi,24094199,Casa,712500.0,2014-09-26
630,Doutor Silveira,Rua,Vila Barreto Clara,Niteroi,24333476,Casa,782500.0,2014-10-08
631,Flor do Campo,Alameda,Vila Barreto Clara,Niteroi,24078827,Casa,296000.0,2016-09-24
632,Porto das Flores,Praca,Vila Barreto Clara,Niteroi,24063629,Apartamento,690000.0,2019-05-13
633,Raul Peixoto,Travessa,Vila Barreto Clara,Niteroi,24065001,Apartamento,465000.0,2019-07-19
634,Augusto Ferraz,Rua,Vila Barreto Clara,Niteroi,24093054,Apartamento,480000.0,2019-12-01
635,das Cerejeiras Leste,Viela,Vila Barreto Clara,Niteroi,24177203,Casa,576000.0,2021-01-16
636,Santa Cecilia,Rua,Vila Barreto Clara,Niteroi,24237720,Casa,992500.0,2022-02-14
637,das Violetas,Avenida,Vila Barreto Clara,Niteroi,24323054,Casa,770000.0,2023-05-07
638,Monte Claro,Rua,Vila Barreto Clara,Niteroi,24143528,Apartamento,712500.0,2023-08-17
639,das Mangueiras,Rua,Vila Barreto Clara,Niteroi,24029591,Apartamento,431000.0,2023-11-16
640,Doutor Silveira,Travessa,Vila Barreto Clara,Niteroi,24022030,Sobrado,970000.0,2024-03-30
641,Sete Colinas,Avenida,Vila Barreto Clara,Niteroi,24324507,Apartamento,612500.0,2024-05-21
642,Campo Sereno Central,Rua,Vila Santa Rosa Alta,Niteroi,24040242,Casa,945000.0,2014-07-01
643,Horizonte Azul Central,Rua,Vila Santa Rosa Alta,Niteroi,24103902,Kitnet,127000.0,2018-02-26
644,Irene Barbosa,Avenida,Vila Santa Rosa Alta,Niteroi,24191741,Casa,977500.0,2021-01-20
645,Monte Claro,Rua,Vila Santa Rosa Alta,Niteroi,24237964,Casa,762500.0,2021-10-16
646,das Figueiras,Avenida,Vila Santa Rosa Alta,Niteroi,24091612,Casa,1620000.0,2022-04-04
647,Sao Gabriel,Rua,Vila Santa Rosa Alta,Niteroi,24309242,Sala Comercial,542000.0,2023-05-28
648,Morro Azul,Rua,Vila Santa Rosa Alta,Niteroi,24243443,Casa,912500.0,2023-12-16
649,Flor do Campo,Rua,Vila Santa Rosa Alta,Niteroi,24256807,Apartamento,965000.0,2024-09-18
650,Primavera,Avenida,Vila Santa Rosa Alta,Niteroi,24090023,Sala Comercial,1177500.0,2024-09-19

In [24]:
# Exiba os imóveis cujo tipo seja "apartamento".
# Aqui fiz direto sem criar variável 

df[df["tipo"] == "Apartamento"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
11,Clara Nogueira,Rua,Alto da Pedreira,Belo Horizonte,30333799,Apartamento,1030000.0,2024-10-15
13,Vale Verde,Rua,Alto da Pedreira,Belo Horizonte,31460215,Apartamento,947500.0,2026-03-07
14,Veredas do Lago,Avenida,Jardim Horizonte Azul,Belo Horizonte,30457770,Apartamento,256000.0,2014-09-24
22,Sao Gabriel,Avenida,Jardim Horizonte Azul,Belo Horizonte,31365999,Apartamento,665000.0,2022-03-23
...,...,...,...,...,...,...,...,...
1476,Helena Sampaio Central,Rua,Vila Primavera,Sao Paulo,5173887,Apartamento,551000.0,2014-11-06
1479,Sao Gabriel,Avenida,Vila Primavera,Sao Paulo,1820839,Apartamento,349000.0,2015-12-10
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1485,Serra Bonita,Rua,Vila Primavera,Sao Paulo,5813517,Apartamento,842500.0,2018-02-09
1493,Engenheiro Tavares,Rua,Vila Primavera,Sao Paulo,4420706,Apartamento,982500.0,2023-09-26

In [25]:
# Exiba os imóveis cujo tipo seja "apartamento".
# Aqui fiz criando variável 

df_apartamento = df[df["tipo"] == "Apartamento"]

df_apartamento

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
11,Clara Nogueira,Rua,Alto da Pedreira,Belo Horizonte,30333799,Apartamento,1030000.0,2024-10-15
13,Vale Verde,Rua,Alto da Pedreira,Belo Horizonte,31460215,Apartamento,947500.0,2026-03-07
14,Veredas do Lago,Avenida,Jardim Horizonte Azul,Belo Horizonte,30457770,Apartamento,256000.0,2014-09-24
22,Sao Gabriel,Avenida,Jardim Horizonte Azul,Belo Horizonte,31365999,Apartamento,665000.0,2022-03-23
...,...,...,...,...,...,...,...,...
1476,Helena Sampaio Central,Rua,Vila Primavera,Sao Paulo,5173887,Apartamento,551000.0,2014-11-06
1479,Sao Gabriel,Avenida,Vila Primavera,Sao Paulo,1820839,Apartamento,349000.0,2015-12-10
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1485,Serra Bonita,Rua,Vila Primavera,Sao Paulo,5813517,Apartamento,842500.0,2018-02-09
1493,Engenheiro Tavares,Rua,Vila Primavera,Sao Paulo,4420706,Apartamento,982500.0,2023-09-26

In [26]:
# Exiba apena as coluna: logradouro
# Note que seu criar aqui com um[]  fica com o formato abaixo sem o nome da coluna  mas  se eu criar com dois [] conforme no próximo notebook fica com o nome

df["logradouro"]
# Nesse caso como não vamos usar essas duas colunas para outras coisas, só pra esse exercicio, não precisei criar
# uma variável, mas se eu fosse usar várias vezes, ai teria que usar uma variável para faciliar .

0                Quinta do Sol
1             Antonio Loureiro
2       Canario Branco Central
3                das Palmeiras
4             Antonio Loureiro
                 ...
1495           Veredas do Lago
1496                  dos Ipes
1497           Benedito Campos
1498                Joao Marin
1499               Monte Claro
Name: logradouro, Length: 1500, dtype: str

In [27]:
# Exiba apena as coluna: logradouro
# Note que seu criar aqui com um[]  fica com o formato acima sem o nome da coluna  mas  se eu criar com dois [] conforme no próximo notebook fica com o nome

df[["logradouro"]]
# Nesse caso como não vamos usar essas duas colunas para outras coisas, só pra esse exercicio, não precisei criar
# uma variável, mas se eu fosse usar várias vezes, ai teria que usar uma variável para faciliar .

                  logradouro
0              Quinta do Sol
1           Antonio Loureiro
2     Canario Branco Central
3              das Palmeiras
4           Antonio Loureiro
...                      ...
1495         Veredas do Lago
1496                dos Ipes
1497         Benedito Campos
1498              Joao Marin
1499             Monte Claro

[1500 rows x 1 columns]

In [28]:
# Exiba apenas as colunas: logradouro e valor dos imóveis.
# Nesse caso como não vamos usar essas duas colunas para outras coisas, só pra esse exercicio, não precisei criar
# uma variável, mas se eu fosse usar várias vezes, ai teria que usar uma variável para faciliar . 

df[["logradouro" ,"valor"]]

                  logradouro      valor
0              Quinta do Sol  1192500.0
1           Antonio Loureiro  1127500.0
2     Canario Branco Central   247000.0
3              das Palmeiras  2095000.0
4           Antonio Loureiro  1392500.0
...                      ...        ...
1495         Veredas do Lago  1132500.0
1496                dos Ipes  1700000.0
1497         Benedito Campos   757500.0
1498              Joao Marin  2205000.0
1499             Monte Claro   279000.0

[1500 rows x 2 columns]

In [29]:
# Exiba os imóveis com valor maior que 900000.
# Nesse caso se eu usar "" nos 900000 ele converte esse número em string e da erro. Número é sempre sem aspas. 
# normalmente no pandas não usamos o print , o print é mais usado na lógica de programação . 
# Mesmo esquema , aqui temos um df filtrado . Se eu quiser ficar usando ele o ideal é guardar em uma variável. 


df[df["valor"] > 900000]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
6,Morro Azul Sul,Rua,Alto da Pedreira,Belo Horizonte,31080395,Terreno,1017500.0,2021-04-13
...,...,...,...,...,...,...,...,...
1492,Laura Amaral,Rodovia,Vila Primavera,Sao Paulo,2159358,Casa,977500.0,2023-07-13
1493,Engenheiro Tavares,Rua,Vila Primavera,Sao Paulo,4420706,Apartamento,982500.0,2023-09-26
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04

In [30]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei duas variáveis , no note abaixo vou fazer criando uma variável só 

df_BH = df[df["cidade"] == "Belo Horizonte"]

df_media_valor_BH =  df_BH["valor"].mean()

df_media_valor_BH

np.float64(771758.3892617449)

In [31]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei apenas com uma variável 
# No notebook vou criar sem variável 


media_valor_BH = df[df["cidade"] == "Belo Horizonte"]

media_valor_BH = df[df["cidade"] == "Belo Horizonte"]["valor"].mean()

media_valor_BH

np.float64(771758.3892617449)

In [32]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei apenas com uma variável 
# No notebook vou criar sem variável 
# ou assim 


media_valor_BH = df[df["cidade"] == "Belo Horizonte"]

media_valor_BH = media_valor_BH["valor"].mean()

media_valor_BH

np.float64(771758.3892617449)

In [33]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei sem nenhuma variável 
# aqui eu não separei por & porque só tem um filtro 
# o que caracteriza um filtro é ter uma comparação (==, >=, <=, >, <, !=)

df[df["cidade"]=="Belo Horizonte"]["valor"].mean()

np.float64(771758.3892617449)

In [34]:
# Exiba os imóveis com valor entre 300000 e 600000 da cidade Curitiba.
# sem variável 
# Conforme aprendi  o () chama a função e o [] acessa uma coluna e filtra dados também . Só que aqui  achamos mais uma função para () que seria separar as condições e isso é comum
# quando tem o & no script. 
# aqui eu  usei   & porque tem mais de um filtro.
# # o que caracteriza um filtro é ter uma comparação (==, >=, <=, >, <, !=) 

df[(df["cidade"] == "Curitiba") & (df["valor"] >= 300000) & (df["valor"] <= 600000)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
256,Helena Sampaio Oeste,Travessa,Alto Capivari,Curitiba,81331041,Casa,368000.0,2017-01-05
257,das Figueiras,Viela,Alto Capivari,Curitiba,80335358,Casa,586000.0,2017-02-22
260,dos Jacarandas Central,Avenida,Alto Capivari,Curitiba,80812544,Kitnet,370000.0,2022-01-17
264,Augusto Ferraz,Rua,Alto Capivari,Curitiba,81289759,Apartamento,506000.0,2024-11-06
269,Porto das Flores,Avenida,Bairro das Industrias,Curitiba,82056016,Casa,362000.0,2014-09-03
273,Doutor Silveira Central,Rua,Bairro das Industrias,Curitiba,80766697,Apartamento,404000.0,2019-09-09
277,das Palmeiras Norte,Rua,Bairro das Industrias,Curitiba,81348042,Casa,449000.0,2023-12-05
282,Comendador Prado,Praca,Campo Alegre Sul,Curitiba,81696505,Apartamento,547000.0,2015-03-14
283,Professor Almeida,Rua,Campo Alegre Sul,Curitiba,81644846,Apartamento,443000.0,2015-12-26
285,das Acacias,Praca,Campo Alegre Sul,Curitiba,81208279,Apartamento,368000.0,2016-10-16
286,das Violetas,Praca,Campo Alegre Sul,Curitiba,82549262,Apartamento,330000.0,2017-01-16
289,Doutor Silveira,Alameda,Campo Alegre Sul,Curitiba,82064350,Terreno,454000.0,2021-10-27
291,Ribeirao Claro,Rua,Campo Alegre Sul,Curitiba,82183830,Casa,546000.0,2022-11-20
294,Augusto Ferraz Sul,Rodovia,Jardim Araucaria,Curitiba,80412787,Casa,460000.0,2016-03-09
300,Maria Valenca,Avenida,Jardim Araucaria,Curitiba,81273461,Apartamento,439000.0,2020-05-21
306,das Violetas,Rua,Jardim das Estacoes,Curitiba,80208846,Apartamento,315000.0,2015-10-02
307,Maria Valenca,Rua,Jardim das Estacoes,Curitiba,81715855,Apartamento,521000.0,2015-12-06
308,Sete Colinas,Rua,Jardim das Estacoes,Curitiba,81218379,Apartamento,542000.0,2016-08-08
310,Canario Branco,Rodovia,Jardim das Estacoes,Curitiba,82438690,Apartamento,549000.0,2017-04-26
311,Veredas do Lago,Rua,Jardim das Estacoes,Curitiba,80327824,Apartamento,330000.0,2017-08-18
315,Antonio Loureiro,Travessa,Jardim das Estacoes,Curitiba,82353228,Sala Comercial,498000.0,2019-12-20
317,Raul Peixoto,Avenida,Jardim das Estacoes,Curitiba,82773083,Apartamento,350000.0,2021-08-15
319,Porto das Flores,Travessa,Jardim das Estacoes,Curitiba,82705603,Apartamento,306000.0,2022-07-20
324,Santa Cecilia Norte,Avenida,Parque Barigui Novo,Curitiba,82657967,Casa,596000.0,2015-12-20
326,Sao Vicente,Rua,Parque Barigui Novo,Curitiba,82989685,Apartamento,334000.0,2018-02-13
327,Irene Barbosa,Travessa,Parque Barigui Novo,Curitiba,82781817,Sala Comercial,438000.0,2018-07-20
333,Olivia Monteiro Central,Rua,Parque Barigui Novo,Curitiba,81322866,Kitnet,466000.0,2024-10-21
338,Maria Valenca,Rua,Residencial Tingui,Curitiba,81220782,Apartamento,401000.0,2014-05-05
340,Laura Amaral,Rua,Residencial Tingui,Curitiba,81579745,Terreno,372000.0,2019-01-16
345,Augusto Ferraz Sul,Alameda,Vila Neve Branca,Curitiba,80501872,Casa,311000.0,2014-09-04
347,Sao Vicente,Avenida,Vila Neve Branca,Curitiba,80602356,Sobrado,540000.0,2016-09-26
348,Dona Celina Sul,Avenida,Vila Neve Branca,Curitiba,82362525,Apartamento,598000.0,2017-08-04
349,Benedito Campos,Rua,Vila Neve Branca,Curitiba,82449254,Casa,378000.0,2019-06-02
350,das Acacias,Rua,Vila Neve Branca,Curitiba,81847544,Apartamento,335000.0,2020-09-01
352,Flor do Campo,Rua,Vila Neve Branca,Curitiba,82345656,Apartamento,524000.0,2021-04-15
356,Sol Nascente,Estrada,Vila Pinheiros,Curitiba,80328066,Apartamento,501000.0,2017-01-30
358,das Palmeiras,Rua,Vila Pinheiros,Curitiba,82037190,Apartamento,500000.0,2018-06-09
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09

In [35]:
# Exiba os imóveis com valor entre 300000 e 600000 da cidade Curitiba.
# aqui eu consegui fazer criando uma variável 

df_curitiba = df[df["cidade"] == "Curitiba"]

df_curitiba = df_curitiba[(df_curitiba["valor"] >= 300000) & (df_curitiba["valor"] <= 600000)]

df_curitiba

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
256,Helena Sampaio Oeste,Travessa,Alto Capivari,Curitiba,81331041,Casa,368000.0,2017-01-05
257,das Figueiras,Viela,Alto Capivari,Curitiba,80335358,Casa,586000.0,2017-02-22
260,dos Jacarandas Central,Avenida,Alto Capivari,Curitiba,80812544,Kitnet,370000.0,2022-01-17
264,Augusto Ferraz,Rua,Alto Capivari,Curitiba,81289759,Apartamento,506000.0,2024-11-06
269,Porto das Flores,Avenida,Bairro das Industrias,Curitiba,82056016,Casa,362000.0,2014-09-03
273,Doutor Silveira Central,Rua,Bairro das Industrias,Curitiba,80766697,Apartamento,404000.0,2019-09-09
277,das Palmeiras Norte,Rua,Bairro das Industrias,Curitiba,81348042,Casa,449000.0,2023-12-05
282,Comendador Prado,Praca,Campo Alegre Sul,Curitiba,81696505,Apartamento,547000.0,2015-03-14
283,Professor Almeida,Rua,Campo Alegre Sul,Curitiba,81644846,Apartamento,443000.0,2015-12-26
285,das Acacias,Praca,Campo Alegre Sul,Curitiba,81208279,Apartamento,368000.0,2016-10-16
286,das Violetas,Praca,Campo Alegre Sul,Curitiba,82549262,Apartamento,330000.0,2017-01-16
289,Doutor Silveira,Alameda,Campo Alegre Sul,Curitiba,82064350,Terreno,454000.0,2021-10-27
291,Ribeirao Claro,Rua,Campo Alegre Sul,Curitiba,82183830,Casa,546000.0,2022-11-20
294,Augusto Ferraz Sul,Rodovia,Jardim Araucaria,Curitiba,80412787,Casa,460000.0,2016-03-09
300,Maria Valenca,Avenida,Jardim Araucaria,Curitiba,81273461,Apartamento,439000.0,2020-05-21
306,das Violetas,Rua,Jardim das Estacoes,Curitiba,80208846,Apartamento,315000.0,2015-10-02
307,Maria Valenca,Rua,Jardim das Estacoes,Curitiba,81715855,Apartamento,521000.0,2015-12-06
308,Sete Colinas,Rua,Jardim das Estacoes,Curitiba,81218379,Apartamento,542000.0,2016-08-08
310,Canario Branco,Rodovia,Jardim das Estacoes,Curitiba,82438690,Apartamento,549000.0,2017-04-26
311,Veredas do Lago,Rua,Jardim das Estacoes,Curitiba,80327824,Apartamento,330000.0,2017-08-18
315,Antonio Loureiro,Travessa,Jardim das Estacoes,Curitiba,82353228,Sala Comercial,498000.0,2019-12-20
317,Raul Peixoto,Avenida,Jardim das Estacoes,Curitiba,82773083,Apartamento,350000.0,2021-08-15
319,Porto das Flores,Travessa,Jardim das Estacoes,Curitiba,82705603,Apartamento,306000.0,2022-07-20
324,Santa Cecilia Norte,Avenida,Parque Barigui Novo,Curitiba,82657967,Casa,596000.0,2015-12-20
326,Sao Vicente,Rua,Parque Barigui Novo,Curitiba,82989685,Apartamento,334000.0,2018-02-13
327,Irene Barbosa,Travessa,Parque Barigui Novo,Curitiba,82781817,Sala Comercial,438000.0,2018-07-20
333,Olivia Monteiro Central,Rua,Parque Barigui Novo,Curitiba,81322866,Kitnet,466000.0,2024-10-21
338,Maria Valenca,Rua,Residencial Tingui,Curitiba,81220782,Apartamento,401000.0,2014-05-05
340,Laura Amaral,Rua,Residencial Tingui,Curitiba,81579745,Terreno,372000.0,2019-01-16
345,Augusto Ferraz Sul,Alameda,Vila Neve Branca,Curitiba,80501872,Casa,311000.0,2014-09-04
347,Sao Vicente,Avenida,Vila Neve Branca,Curitiba,80602356,Sobrado,540000.0,2016-09-26
348,Dona Celina Sul,Avenida,Vila Neve Branca,Curitiba,82362525,Apartamento,598000.0,2017-08-04
349,Benedito Campos,Rua,Vila Neve Branca,Curitiba,82449254,Casa,378000.0,2019-06-02
350,das Acacias,Rua,Vila Neve Branca,Curitiba,81847544,Apartamento,335000.0,2020-09-01
352,Flor do Campo,Rua,Vila Neve Branca,Curitiba,82345656,Apartamento,524000.0,2021-04-15
356,Sol Nascente,Estrada,Vila Pinheiros,Curitiba,80328066,Apartamento,501000.0,2017-01-30
358,das Palmeiras,Rua,Vila Pinheiros,Curitiba,82037190,Apartamento,500000.0,2018-06-09
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09

In [36]:
#  Exiba os imóveis com data de aquisição posterior a 2020-01-01.

df_data_especifica = df[df["data_aquisicao"] > "2020-01-01"]

df_data_especifica

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
6,Morro Azul Sul,Rua,Alto da Pedreira,Belo Horizonte,31080395,Terreno,1017500.0,2021-04-13
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
8,Flor do Campo,Rua,Alto da Pedreira,Belo Horizonte,30733234,Loja,1355000.0,2023-01-24
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [37]:
#  Exiba os imóveis com data de aquisição posterior a 2020-01-01.
# Ou de uma forma mais simples sem variáveis , e aqui mostra que em alguns casos eu tenho que usar variável
# e em outras não .
#  Exiba os imóveis com data de aquisição posterior a 2020-01-01.

df[df["data_aquisicao"] > "2020-01-01"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
6,Morro Azul Sul,Rua,Alto da Pedreira,Belo Horizonte,31080395,Terreno,1017500.0,2021-04-13
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
8,Flor do Campo,Rua,Alto da Pedreira,Belo Horizonte,30733234,Loja,1355000.0,2023-01-24
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [38]:
#Exiba os imóveis que não sejam do tipo "apartamento" e tenham valor menor ou igual a 600000.
# aqui fiz sem variáveis . 

df[(df["tipo"] != "Apartamento") & (df["valor"] <= 600000)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
15,Laranjeiras,Avenida,Jardim Horizonte Azul,Belo Horizonte,31728489,Casa,418000.0,2015-01-27
16,dos Ipes,Avenida,Jardim Horizonte Azul,Belo Horizonte,31849968,Casa,346000.0,2015-02-22
...,...,...,...,...,...,...,...,...
1436,Flor do Campo,Avenida,Vila Horizonte,Sao Paulo,4868406,Sala Comercial,540000.0,2018-02-09
1481,Ribeirao Claro Norte,Rua,Vila Primavera,Sao Paulo,4841355,Casa,447000.0,2016-05-12
1486,Porto das Flores,Avenida,Vila Primavera,Sao Paulo,5813031,Kitnet,222000.0,2018-10-12
1489,Capitao Noronha,Rua,Vila Primavera,Sao Paulo,2712517,Kitnet,245000.0,2022-04-07
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [ ]:
#Exiba os imóveis que não sejam do tipo "apartamento" e tenham valor menor ou igual a 600000.
# Já nesse criei uma variável . 

df_filtrado = df[(df["tipo"] != "Apartamento") & (df["valor"] <= 600000)]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
15,Laranjeiras,Avenida,Jardim Horizonte Azul,Belo Horizonte,31728489,Casa,418000.0,2015-01-27
16,dos Ipes,Avenida,Jardim Horizonte Azul,Belo Horizonte,31849968,Casa,346000.0,2015-02-22
...,...,...,...,...,...,...,...,...
1436,Flor do Campo,Avenida,Vila Horizonte,Sao Paulo,4868406,Sala Comercial,540000.0,2018-02-09
1481,Ribeirao Claro Norte,Rua,Vila Primavera,Sao Paulo,4841355,Casa,447000.0,2016-05-12
1486,Porto das Flores,Avenida,Vila Primavera,Sao Paulo,5813031,Kitnet,222000.0,2018-10-12
1489,Capitao Noronha,Rua,Vila Primavera,Sao Paulo,2712517,Kitnet,245000.0,2022-04-07
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [ ]:
# Exiba os imóveis da cidade "Curitiba" cujo bairro não seja "Residencial Tingui".
# aqui fiz  sem variável . 

df[(df["cidade"] == "Curitiba") & (df["bairro"] != "Residencial Tingui")]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [54]:
# Exiba os imóveis da cidade "Curitiba" cujo bairro não seja "Residencial Tingui".
# aqui fiz com variável. 

df_filtrado = df[(df["cidade"] == "Curitiba") & (df["bairro"] != "Residencial Tingui")]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [59]:
# Exiba os imóveis cujo valor seja maior que a média geral e cuja data de aquisição seja anterior a 2021-01-01.

df_valor_medio =  df["valor"].mean()

df_filtrado = df[(df_valor_medio < df["valor"]) & (df["data_aquisicao"] < "2021-01-01")]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
17,Antonio Loureiro,Rua,Jardim Horizonte Azul,Belo Horizonte,31840545,Galpao,2490000.0,2015-05-05
...,...,...,...,...,...,...,...,...
1480,Flor do Campo Central,Rua,Vila Primavera,Sao Paulo,2889729,Casa,1082500.0,2016-02-08
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1484,Helena Sampaio Oeste,Avenida,Vila Primavera,Sao Paulo,2557295,Casa,1345000.0,2017-07-02
1487,das Mangueiras,Largo,Vila Primavera,Sao Paulo,4122666,Sobrado,1407500.0,2020-10-01
1488,Raul Peixoto Norte,Rua,Vila Primavera,Sao Paulo,4063339,Casa,1127500.0,2020-10-17

In [ ]:
# esse comando me mostra o tamanho que cada coluna ocupa , por exemplo, o logradouro ocupa 94 mil bytes que é igual 94 kb

df.memory_usage (deep=True)

Index                 132
logradouro          94765
tipo_logradouro     80850
bairro             100437
cidade              89014
cep                 12000
tipo                85015
valor               12000
data_aquisicao      12000
dtype: int64