In [5]:
import pandas as pd 

df = pd.read_excel("imoveis_aquisicoes_brasil.xlsx")

df

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [6]:
# nesse caso o len mostra a quatidade de linhas 

print(len(df))

1500

In [7]:
# aqui o len já mostra a quantidade de colunas 
print(len(df.columns))

8

In [8]:
# b) Quantas colunas numéricas o dataset possui?
# lembrando que o dataset é o conjunto de dados que estão na minha tabela  e o projeto é a pasta
# que tem essa tabela mas também tem o notebook (.ipynb) com o código, o ambiente virtual Venv, 
# as bibliotecas  e etc...

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   logradouro       1500 non-null   str
 1   tipo_logradouro  1500 non-null   str
 2   bairro           1500 non-null   str
 3   cidade           1500 non-null   str
 4   cep              1500 non-null   int64
 5   tipo             1500 non-null   str
 6   valor            1500 non-null   float64
 7   data_aquisicao   1500 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 93.9 KB

In [9]:
# b) Quantas colunas numéricas o dataset possui?
# já nesse caso  ele mostra já calculado a quantidade de colunas por tipo. 
# df.dtypes = lista o tipo de cada coluna 
# .value_counts()  conta quantas colunas tem por esses tipos que eu listei no df.dtypes

df.dtypes.value_counts()

str               5
int64             1
float64           1
datetime64[us]    1
Name: count, dtype: int64

In [10]:
# d) Escreva o endereço completo do imóvel com o menor valor 
# esse sort_values  ordena os valores do menor para o maior 

df.sort_values("valor")

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
...,...,...,...,...,...,...,...,...
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17

In [11]:
# d) Escreva o endereço completo do imóvel com o maior valor 
# esse sort_values (coluna , ascending=False) ordena os valores do maior para o menor. 

df.sort_values("valor" , ascending=False)

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
...,...,...,...,...,...,...,...,...
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10

In [12]:
# Calcule a soma dos valores de todos os imóveis da tabela
# quando vou acessar uma coluna é sempre [] e quando vou chamar uma função  é sempre  ()
# [] = pegar/filtrar dados
# () = executar algo (função/método)

df['valor'].sum()

np.float64(1316455000.0)

In [13]:
# Calcule a soma dos valores de todos os imóveis da tabela
soma = df["valor"].sum()

print(f"A soma dos valores dos imóveis é de R$ {soma}")

A soma dos valores dos imóveis é de R$ 1316455000.0

In [14]:
# Calcule a soma dos valores de todos os imóveis da tabela
# aqui usei o print de um jeito diferente , somei string com a variável soma  
# mas o que está dentro dessa variável tem que ser string também , por  isso usei o str

soma = str(df['valor'].sum())
print("A soma dos valores dos imóveis é de R$ " + soma)

A soma dos valores dos imóveis é de R$ 1316455000.0

In [15]:
# Calcule a média dos valores de todos os imóveis da tabela

df['valor'].mean()

np.float64(877636.6666666666)

In [16]:
# Calcule a média dos valores de todos os imóveis da tabela

media= df['valor'].mean()

print(f"A média dos valores dos imóveis é de R$ {media}")

A média dos valores dos imóveis é de R$ 877636.6666666666

In [17]:
# Calcule a mediana dos valores de todos os imóveis da tabela

df['valor'].median()

np.float64(712500.0)

In [21]:
# Calcule a mediana dos valores de todos os imóveis da tabela
# aqui guardei esse valor em uma variável .

mediana_valor = df['valor'].median()

print(f"A mediana dos valores dos imóveis é de R$ {mediana_valor}")

A mediana dos valores dos imóveis é de R$ 712500.0

In [22]:
# Calcule o desvio padrão dos valores de todos os imóveis da tabela


df['valor'].std()

np.float64(646676.0007057745)

In [23]:
# Calcule o desvio padrão dos valores de todos os imóveis da tabela

desvio_padrao = df["valor"].std()

print(f"O desvio padrão dos imóveis é de {desvio_padrao}")

O desvio padrão dos imóveis é de 646676.0007057745

In [24]:
# Exiba apenas os imóveis da cidade "Curitiba"
# desse jeito eu não criei variável. Mas no próximo vou criá-la 
 
df[df["cidade"] == "Curitiba"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [ ]:
# Exiba apenas os imóveis da cidade "Curitiba"

df_Curitiba = df[df["cidade"] == "Curitiba"]


df_Curitiba

In [31]:
# Nesse caso , ele puxou Niteroi porque eu usei o DF original , se eu tivesse usado o df_Curitiba == Niteroi não teria vindo nada  

df_Curitiba = df[df["cidade"] == "Niteroi"]

df_Curitiba

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
597,dos Jacarandas,Rua,Alto da Baia,Niteroi,24318258,Cobertura,1650000.0,2016-01-27
598,Monte Claro Central,Largo,Alto da Baia,Niteroi,24217002,Casa,508000.0,2016-06-13
599,dos Jacarandas Sul,Praca,Alto da Baia,Niteroi,24372192,Terreno,1505000.0,2016-12-29
600,Nova Aurora,Rua,Alto da Baia,Niteroi,24387600,Kitnet,271000.0,2019-05-14
601,Domingos Arantes,Rua,Alto da Baia,Niteroi,24369855,Terreno,950000.0,2019-12-21
602,das Violetas,Rua,Alto da Baia,Niteroi,24346475,Sala Comercial,997500.0,2021-06-03
603,Sol Nascente,Rua,Alto da Baia,Niteroi,24176083,Apartamento,817500.0,2024-07-05
604,Alto do Cedro,Rua,Campo Oceano Verde,Niteroi,24286061,Apartamento,702500.0,2016-12-07
605,das Orquideas,Travessa,Campo Oceano Verde,Niteroi,24391369,Apartamento,453000.0,2017-03-25
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
607,Professor Almeida,Avenida,Jardim Icarai Novo,Niteroi,24016406,Apartamento,905000.0,2015-06-26
608,das Violetas,Travessa,Jardim Icarai Novo,Niteroi,24110292,Apartamento,418000.0,2015-09-04
609,Raul Peixoto,Alameda,Jardim Icarai Novo,Niteroi,24305192,Casa,1362500.0,2018-11-14
610,Paineiras,Avenida,Jardim Icarai Novo,Niteroi,24342897,Apartamento,1237500.0,2026-04-25
611,Canario Branco,Avenida,Parque Fonseca Novo,Niteroi,24228340,Casa,792500.0,2015-11-22
612,Antonio Loureiro,Alameda,Parque Fonseca Novo,Niteroi,24112786,Terreno,875000.0,2016-12-09
613,Engenheiro Tavares,Alameda,Parque Fonseca Novo,Niteroi,24389911,Apartamento,617500.0,2021-07-25
614,Comendador Prado,Avenida,Parque Fonseca Novo,Niteroi,24304314,Sobrado,1372500.0,2023-07-18
615,Horizonte Azul,Avenida,Parque Fonseca Novo,Niteroi,24180462,Loja,1287500.0,2024-08-17
616,Sol Nascente Oeste,Rua,Praia das Conchas,Niteroi,24135666,Casa,705000.0,2014-06-08
617,Clara Nogueira Leste,Rua,Praia das Conchas,Niteroi,24309569,Apartamento,416000.0,2016-06-12
618,Laura Amaral,Avenida,Praia das Conchas,Niteroi,24243851,Apartamento,365000.0,2017-11-27
619,Sao Vicente,Rua,Praia das Conchas,Niteroi,24283038,Cobertura,2895000.0,2021-02-01
620,Vista Alegre,Rua,Praia das Conchas,Niteroi,24051243,Apartamento,660000.0,2021-04-14
621,Augusto Ferraz,Rodovia,Praia das Conchas,Niteroi,24220807,Casa,712500.0,2021-10-27
622,das Cerejeiras,Rua,Praia das Conchas,Niteroi,24105991,Terreno,1520000.0,2024-12-21
623,Flor do Campo Norte,Rua,Residencial Pendotiba Sul,Niteroi,24215230,Apartamento,339000.0,2014-06-12
624,Veredas do Lago,Rua,Residencial Pendotiba Sul,Niteroi,24224208,Apartamento,369000.0,2014-08-10
625,Serra Bonita,Alameda,Residencial Pendotiba Sul,Niteroi,24029352,Chacara,962500.0,2018-10-28
626,Irene Barbosa,Rua,Residencial Pendotiba Sul,Niteroi,24343684,Apartamento,800000.0,2018-12-15
627,das Figueiras Leste,Avenida,Residencial Pendotiba Sul,Niteroi,24266997,Apartamento,492000.0,2022-03-10
628,Vale Verde,Estrada,Vila Barreto Clara,Niteroi,24315298,Sobrado,612500.0,2014-03-19
629,Raul Peixoto,Rua,Vila Barreto Clara,Niteroi,24094199,Casa,712500.0,2014-09-26
630,Doutor Silveira,Rua,Vila Barreto Clara,Niteroi,24333476,Casa,782500.0,2014-10-08
631,Flor do Campo,Alameda,Vila Barreto Clara,Niteroi,24078827,Casa,296000.0,2016-09-24
632,Porto das Flores,Praca,Vila Barreto Clara,Niteroi,24063629,Apartamento,690000.0,2019-05-13
633,Raul Peixoto,Travessa,Vila Barreto Clara,Niteroi,24065001,Apartamento,465000.0,2019-07-19
634,Augusto Ferraz,Rua,Vila Barreto Clara,Niteroi,24093054,Apartamento,480000.0,2019-12-01
635,das Cerejeiras Leste,Viela,Vila Barreto Clara,Niteroi,24177203,Casa,576000.0,2021-01-16
636,Santa Cecilia,Rua,Vila Barreto Clara,Niteroi,24237720,Casa,992500.0,2022-02-14
637,das Violetas,Avenida,Vila Barreto Clara,Niteroi,24323054,Casa,770000.0,2023-05-07
638,Monte Claro,Rua,Vila Barreto Clara,Niteroi,24143528,Apartamento,712500.0,2023-08-17
639,das Mangueiras,Rua,Vila Barreto Clara,Niteroi,24029591,Apartamento,431000.0,2023-11-16
640,Doutor Silveira,Travessa,Vila Barreto Clara,Niteroi,24022030,Sobrado,970000.0,2024-03-30
641,Sete Colinas,Avenida,Vila Barreto Clara,Niteroi,24324507,Apartamento,612500.0,2024-05-21
642,Campo Sereno Central,Rua,Vila Santa Rosa Alta,Niteroi,24040242,Casa,945000.0,2014-07-01
643,Horizonte Azul Central,Rua,Vila Santa Rosa Alta,Niteroi,24103902,Kitnet,127000.0,2018-02-26
644,Irene Barbosa,Avenida,Vila Santa Rosa Alta,Niteroi,24191741,Casa,977500.0,2021-01-20
645,Monte Claro,Rua,Vila Santa Rosa Alta,Niteroi,24237964,Casa,762500.0,2021-10-16
646,das Figueiras,Avenida,Vila Santa Rosa Alta,Niteroi,24091612,Casa,1620000.0,2022-04-04
647,Sao Gabriel,Rua,Vila Santa Rosa Alta,Niteroi,24309242,Sala Comercial,542000.0,2023-05-28
648,Morro Azul,Rua,Vila Santa Rosa Alta,Niteroi,24243443,Casa,912500.0,2023-12-16
649,Flor do Campo,Rua,Vila Santa Rosa Alta,Niteroi,24256807,Apartamento,965000.0,2024-09-18
650,Primavera,Avenida,Vila Santa Rosa Alta,Niteroi,24090023,Sala Comercial,1177500.0,2024-09-19

In [ ]:
# Exiba os imóveis cujo tipo seja "apartamento".
# Aqui fiz direto sem criar variável 

df[df["tipo"] == "Apartamento"]

In [30]:
# Exiba os imóveis cujo tipo seja "apartamento".
# Aqui fiz criando variável 

df_apartamento = df[df["tipo"] == "Apartamento"]

df_apartamento

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
11,Clara Nogueira,Rua,Alto da Pedreira,Belo Horizonte,30333799,Apartamento,1030000.0,2024-10-15
13,Vale Verde,Rua,Alto da Pedreira,Belo Horizonte,31460215,Apartamento,947500.0,2026-03-07
14,Veredas do Lago,Avenida,Jardim Horizonte Azul,Belo Horizonte,30457770,Apartamento,256000.0,2014-09-24
22,Sao Gabriel,Avenida,Jardim Horizonte Azul,Belo Horizonte,31365999,Apartamento,665000.0,2022-03-23
...,...,...,...,...,...,...,...,...
1476,Helena Sampaio Central,Rua,Vila Primavera,Sao Paulo,5173887,Apartamento,551000.0,2014-11-06
1479,Sao Gabriel,Avenida,Vila Primavera,Sao Paulo,1820839,Apartamento,349000.0,2015-12-10
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1485,Serra Bonita,Rua,Vila Primavera,Sao Paulo,5813517,Apartamento,842500.0,2018-02-09
1493,Engenheiro Tavares,Rua,Vila Primavera,Sao Paulo,4420706,Apartamento,982500.0,2023-09-26

In [29]:
# Exiba apena as coluna: logradouro
# Note que seu criar aqui com um[]  fica com o formato abaixo sem o nome da coluna  mas  se eu criar com dois [] conforme no próximo notebook fica com o nome

df["logradouro"]
# Nesse caso como não vamos usar essas duas colunas para outras coisas, só pra esse exercicio, não precisei criar
# uma variável, mas se eu fosse usar várias vezes, ai teria que usar uma variável para faciliar .

0                Quinta do Sol
1             Antonio Loureiro
2       Canario Branco Central
3                das Palmeiras
4             Antonio Loureiro
                 ...
1495           Veredas do Lago
1496                  dos Ipes
1497           Benedito Campos
1498                Joao Marin
1499               Monte Claro
Name: logradouro, Length: 1500, dtype: str

In [28]:
# Exiba apena as coluna: logradouro
# Note que seu criar aqui com um[]  fica com o formato acima sem o nome da coluna  mas  se eu criar com dois [] conforme no próximo notebook fica com o nome

df[["logradouro"]]
# Nesse caso como não vamos usar essas duas colunas para outras coisas, só pra esse exercicio, não precisei criar
# uma variável, mas se eu fosse usar várias vezes, ai teria que usar uma variável para faciliar .

                  logradouro
0              Quinta do Sol
1           Antonio Loureiro
2     Canario Branco Central
3              das Palmeiras
4           Antonio Loureiro
...                      ...
1495         Veredas do Lago
1496                dos Ipes
1497         Benedito Campos
1498              Joao Marin
1499             Monte Claro

[1500 rows x 1 columns]

In [27]:
# Exiba apenas as colunas: logradouro e valor dos imóveis.
# Nesse caso como não vamos usar essas duas colunas para outras coisas, só pra esse exercicio, não precisei criar
# uma variável, mas se eu fosse usar várias vezes, ai teria que usar uma variável para faciliar . 

df[["logradouro" ,"valor"]]

                  logradouro      valor
0              Quinta do Sol  1192500.0
1           Antonio Loureiro  1127500.0
2     Canario Branco Central   247000.0
3              das Palmeiras  2095000.0
4           Antonio Loureiro  1392500.0
...                      ...        ...
1495         Veredas do Lago  1132500.0
1496                dos Ipes  1700000.0
1497         Benedito Campos   757500.0
1498              Joao Marin  2205000.0
1499             Monte Claro   279000.0

[1500 rows x 2 columns]

In [32]:
# Exiba os imóveis com valor maior que 900000.
# Nesse caso se eu usar "" nos 900000 ele converte esse número em string e da erro. Número é sempre sem aspas. 
# normalmente no pandas não usamos o print , o print é mais usado na lógica de programação . 
# Mesmo esquema , aqui temos um df filtrado . Se eu quiser ficar usando ele o ideal é guardar em uma variável. 


df[df["valor"] > 900000]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
6,Morro Azul Sul,Rua,Alto da Pedreira,Belo Horizonte,31080395,Terreno,1017500.0,2021-04-13
...,...,...,...,...,...,...,...,...
1492,Laura Amaral,Rodovia,Vila Primavera,Sao Paulo,2159358,Casa,977500.0,2023-07-13
1493,Engenheiro Tavares,Rua,Vila Primavera,Sao Paulo,4420706,Apartamento,982500.0,2023-09-26
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04

In [25]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei duas variáveis , no note abaixo vou fazer criando uma variável só 

df_BH = df[df["cidade"] == "Belo Horizonte"]

df_media_valor_BH =  df_BH["valor"].mean()

df_media_valor_BH

np.float64(771758.3892617449)

In [33]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei apenas com uma variável 
# No notebook vou criar sem variável 


media_valor_BH = df[df["cidade"] == "Belo Horizonte"]

media_valor_BH = df[df["cidade"] == "Belo Horizonte"]["valor"].mean()

media_valor_BH

np.float64(771758.3892617449)

In [34]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# aqui com uma variável só e em menos linhas . 

media_valor_BH = df[df["cidade"] == "Belo Horizonte"]["valor"].mean()

media_valor_BH

np.float64(771758.3892617449)

In [35]:
# Exiba a média de valores dos imóveis da cidade "Belo Horizonte".
# Aqui eu criei sem nenhuma variável 
# aqui eu não separei por & porque só tem um filtro 
# o que caracteriza um filtro é ter uma comparação (==, >=, <=, >, <, !=)

df[df["cidade"]=="Belo Horizonte"]["valor"].mean()

np.float64(771758.3892617449)

In [36]:
# Exiba os imóveis com valor entre 300000 e 600000 da cidade Curitiba.
# sem variável 
# Conforme aprendi  o () chama a função e o [] acessa uma coluna e filtra dados também . Só que aqui  achamos mais uma função para () que seria separar as condições e isso é comum
# quando tem o & no script. 
# aqui eu  usei   & porque tem mais de um filtro.
# # o que caracteriza um filtro é ter uma comparação (==, >=, <=, >, <, !=) 

df[(df["cidade"] == "Curitiba") & (df["valor"] >= 300000) & (df["valor"] <= 600000)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
256,Helena Sampaio Oeste,Travessa,Alto Capivari,Curitiba,81331041,Casa,368000.0,2017-01-05
257,das Figueiras,Viela,Alto Capivari,Curitiba,80335358,Casa,586000.0,2017-02-22
260,dos Jacarandas Central,Avenida,Alto Capivari,Curitiba,80812544,Kitnet,370000.0,2022-01-17
264,Augusto Ferraz,Rua,Alto Capivari,Curitiba,81289759,Apartamento,506000.0,2024-11-06
269,Porto das Flores,Avenida,Bairro das Industrias,Curitiba,82056016,Casa,362000.0,2014-09-03
273,Doutor Silveira Central,Rua,Bairro das Industrias,Curitiba,80766697,Apartamento,404000.0,2019-09-09
277,das Palmeiras Norte,Rua,Bairro das Industrias,Curitiba,81348042,Casa,449000.0,2023-12-05
282,Comendador Prado,Praca,Campo Alegre Sul,Curitiba,81696505,Apartamento,547000.0,2015-03-14
283,Professor Almeida,Rua,Campo Alegre Sul,Curitiba,81644846,Apartamento,443000.0,2015-12-26
285,das Acacias,Praca,Campo Alegre Sul,Curitiba,81208279,Apartamento,368000.0,2016-10-16
286,das Violetas,Praca,Campo Alegre Sul,Curitiba,82549262,Apartamento,330000.0,2017-01-16
289,Doutor Silveira,Alameda,Campo Alegre Sul,Curitiba,82064350,Terreno,454000.0,2021-10-27
291,Ribeirao Claro,Rua,Campo Alegre Sul,Curitiba,82183830,Casa,546000.0,2022-11-20
294,Augusto Ferraz Sul,Rodovia,Jardim Araucaria,Curitiba,80412787,Casa,460000.0,2016-03-09
300,Maria Valenca,Avenida,Jardim Araucaria,Curitiba,81273461,Apartamento,439000.0,2020-05-21
306,das Violetas,Rua,Jardim das Estacoes,Curitiba,80208846,Apartamento,315000.0,2015-10-02
307,Maria Valenca,Rua,Jardim das Estacoes,Curitiba,81715855,Apartamento,521000.0,2015-12-06
308,Sete Colinas,Rua,Jardim das Estacoes,Curitiba,81218379,Apartamento,542000.0,2016-08-08
310,Canario Branco,Rodovia,Jardim das Estacoes,Curitiba,82438690,Apartamento,549000.0,2017-04-26
311,Veredas do Lago,Rua,Jardim das Estacoes,Curitiba,80327824,Apartamento,330000.0,2017-08-18
315,Antonio Loureiro,Travessa,Jardim das Estacoes,Curitiba,82353228,Sala Comercial,498000.0,2019-12-20
317,Raul Peixoto,Avenida,Jardim das Estacoes,Curitiba,82773083,Apartamento,350000.0,2021-08-15
319,Porto das Flores,Travessa,Jardim das Estacoes,Curitiba,82705603,Apartamento,306000.0,2022-07-20
324,Santa Cecilia Norte,Avenida,Parque Barigui Novo,Curitiba,82657967,Casa,596000.0,2015-12-20
326,Sao Vicente,Rua,Parque Barigui Novo,Curitiba,82989685,Apartamento,334000.0,2018-02-13
327,Irene Barbosa,Travessa,Parque Barigui Novo,Curitiba,82781817,Sala Comercial,438000.0,2018-07-20
333,Olivia Monteiro Central,Rua,Parque Barigui Novo,Curitiba,81322866,Kitnet,466000.0,2024-10-21
338,Maria Valenca,Rua,Residencial Tingui,Curitiba,81220782,Apartamento,401000.0,2014-05-05
340,Laura Amaral,Rua,Residencial Tingui,Curitiba,81579745,Terreno,372000.0,2019-01-16
345,Augusto Ferraz Sul,Alameda,Vila Neve Branca,Curitiba,80501872,Casa,311000.0,2014-09-04
347,Sao Vicente,Avenida,Vila Neve Branca,Curitiba,80602356,Sobrado,540000.0,2016-09-26
348,Dona Celina Sul,Avenida,Vila Neve Branca,Curitiba,82362525,Apartamento,598000.0,2017-08-04
349,Benedito Campos,Rua,Vila Neve Branca,Curitiba,82449254,Casa,378000.0,2019-06-02
350,das Acacias,Rua,Vila Neve Branca,Curitiba,81847544,Apartamento,335000.0,2020-09-01
352,Flor do Campo,Rua,Vila Neve Branca,Curitiba,82345656,Apartamento,524000.0,2021-04-15
356,Sol Nascente,Estrada,Vila Pinheiros,Curitiba,80328066,Apartamento,501000.0,2017-01-30
358,das Palmeiras,Rua,Vila Pinheiros,Curitiba,82037190,Apartamento,500000.0,2018-06-09
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09

In [37]:
# Exiba os imóveis com valor entre 300000 e 600000 da cidade Curitiba.
# aqui eu consegui fazer criando uma variável 

df_curitiba = df[df["cidade"] == "Curitiba"]

df_curitiba = df_curitiba[(df_curitiba["valor"] >= 300000) & (df_curitiba["valor"] <= 600000)]

df_curitiba

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
256,Helena Sampaio Oeste,Travessa,Alto Capivari,Curitiba,81331041,Casa,368000.0,2017-01-05
257,das Figueiras,Viela,Alto Capivari,Curitiba,80335358,Casa,586000.0,2017-02-22
260,dos Jacarandas Central,Avenida,Alto Capivari,Curitiba,80812544,Kitnet,370000.0,2022-01-17
264,Augusto Ferraz,Rua,Alto Capivari,Curitiba,81289759,Apartamento,506000.0,2024-11-06
269,Porto das Flores,Avenida,Bairro das Industrias,Curitiba,82056016,Casa,362000.0,2014-09-03
273,Doutor Silveira Central,Rua,Bairro das Industrias,Curitiba,80766697,Apartamento,404000.0,2019-09-09
277,das Palmeiras Norte,Rua,Bairro das Industrias,Curitiba,81348042,Casa,449000.0,2023-12-05
282,Comendador Prado,Praca,Campo Alegre Sul,Curitiba,81696505,Apartamento,547000.0,2015-03-14
283,Professor Almeida,Rua,Campo Alegre Sul,Curitiba,81644846,Apartamento,443000.0,2015-12-26
285,das Acacias,Praca,Campo Alegre Sul,Curitiba,81208279,Apartamento,368000.0,2016-10-16
286,das Violetas,Praca,Campo Alegre Sul,Curitiba,82549262,Apartamento,330000.0,2017-01-16
289,Doutor Silveira,Alameda,Campo Alegre Sul,Curitiba,82064350,Terreno,454000.0,2021-10-27
291,Ribeirao Claro,Rua,Campo Alegre Sul,Curitiba,82183830,Casa,546000.0,2022-11-20
294,Augusto Ferraz Sul,Rodovia,Jardim Araucaria,Curitiba,80412787,Casa,460000.0,2016-03-09
300,Maria Valenca,Avenida,Jardim Araucaria,Curitiba,81273461,Apartamento,439000.0,2020-05-21
306,das Violetas,Rua,Jardim das Estacoes,Curitiba,80208846,Apartamento,315000.0,2015-10-02
307,Maria Valenca,Rua,Jardim das Estacoes,Curitiba,81715855,Apartamento,521000.0,2015-12-06
308,Sete Colinas,Rua,Jardim das Estacoes,Curitiba,81218379,Apartamento,542000.0,2016-08-08
310,Canario Branco,Rodovia,Jardim das Estacoes,Curitiba,82438690,Apartamento,549000.0,2017-04-26
311,Veredas do Lago,Rua,Jardim das Estacoes,Curitiba,80327824,Apartamento,330000.0,2017-08-18
315,Antonio Loureiro,Travessa,Jardim das Estacoes,Curitiba,82353228,Sala Comercial,498000.0,2019-12-20
317,Raul Peixoto,Avenida,Jardim das Estacoes,Curitiba,82773083,Apartamento,350000.0,2021-08-15
319,Porto das Flores,Travessa,Jardim das Estacoes,Curitiba,82705603,Apartamento,306000.0,2022-07-20
324,Santa Cecilia Norte,Avenida,Parque Barigui Novo,Curitiba,82657967,Casa,596000.0,2015-12-20
326,Sao Vicente,Rua,Parque Barigui Novo,Curitiba,82989685,Apartamento,334000.0,2018-02-13
327,Irene Barbosa,Travessa,Parque Barigui Novo,Curitiba,82781817,Sala Comercial,438000.0,2018-07-20
333,Olivia Monteiro Central,Rua,Parque Barigui Novo,Curitiba,81322866,Kitnet,466000.0,2024-10-21
338,Maria Valenca,Rua,Residencial Tingui,Curitiba,81220782,Apartamento,401000.0,2014-05-05
340,Laura Amaral,Rua,Residencial Tingui,Curitiba,81579745,Terreno,372000.0,2019-01-16
345,Augusto Ferraz Sul,Alameda,Vila Neve Branca,Curitiba,80501872,Casa,311000.0,2014-09-04
347,Sao Vicente,Avenida,Vila Neve Branca,Curitiba,80602356,Sobrado,540000.0,2016-09-26
348,Dona Celina Sul,Avenida,Vila Neve Branca,Curitiba,82362525,Apartamento,598000.0,2017-08-04
349,Benedito Campos,Rua,Vila Neve Branca,Curitiba,82449254,Casa,378000.0,2019-06-02
350,das Acacias,Rua,Vila Neve Branca,Curitiba,81847544,Apartamento,335000.0,2020-09-01
352,Flor do Campo,Rua,Vila Neve Branca,Curitiba,82345656,Apartamento,524000.0,2021-04-15
356,Sol Nascente,Estrada,Vila Pinheiros,Curitiba,80328066,Apartamento,501000.0,2017-01-30
358,das Palmeiras,Rua,Vila Pinheiros,Curitiba,82037190,Apartamento,500000.0,2018-06-09
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09

In [38]:
#  Exiba os imóveis com data de aquisição posterior a 2020-01-01.

df_data_especifica = df[df["data_aquisicao"] > "2020-01-01"]

df_data_especifica

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
6,Morro Azul Sul,Rua,Alto da Pedreira,Belo Horizonte,31080395,Terreno,1017500.0,2021-04-13
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
8,Flor do Campo,Rua,Alto da Pedreira,Belo Horizonte,30733234,Loja,1355000.0,2023-01-24
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [39]:
#  Exiba os imóveis com data de aquisição posterior a 2020-01-01.
# Ou de uma forma mais simples sem variáveis , e aqui mostra que em alguns casos eu tenho que usar variável
# e em outras não .
#  Exiba os imóveis com data de aquisição posterior a 2020-01-01.

df[df["data_aquisicao"] > "2020-01-01"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
6,Morro Azul Sul,Rua,Alto da Pedreira,Belo Horizonte,31080395,Terreno,1017500.0,2021-04-13
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
8,Flor do Campo,Rua,Alto da Pedreira,Belo Horizonte,30733234,Loja,1355000.0,2023-01-24
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [40]:
#Exiba os imóveis que não sejam do tipo "apartamento" e tenham valor menor ou igual a 600000.
# aqui fiz sem variáveis . 

df[(df["tipo"] != "Apartamento") & (df["valor"] <= 600000)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
15,Laranjeiras,Avenida,Jardim Horizonte Azul,Belo Horizonte,31728489,Casa,418000.0,2015-01-27
16,dos Ipes,Avenida,Jardim Horizonte Azul,Belo Horizonte,31849968,Casa,346000.0,2015-02-22
...,...,...,...,...,...,...,...,...
1436,Flor do Campo,Avenida,Vila Horizonte,Sao Paulo,4868406,Sala Comercial,540000.0,2018-02-09
1481,Ribeirao Claro Norte,Rua,Vila Primavera,Sao Paulo,4841355,Casa,447000.0,2016-05-12
1486,Porto das Flores,Avenida,Vila Primavera,Sao Paulo,5813031,Kitnet,222000.0,2018-10-12
1489,Capitao Noronha,Rua,Vila Primavera,Sao Paulo,2712517,Kitnet,245000.0,2022-04-07
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [41]:
#Exiba os imóveis que não sejam do tipo "apartamento" e tenham valor menor ou igual a 600000.
# Já nesse criei uma variável . 

df_filtrado = df[(df["tipo"] != "Apartamento") & (df["valor"] <= 600000)]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
15,Laranjeiras,Avenida,Jardim Horizonte Azul,Belo Horizonte,31728489,Casa,418000.0,2015-01-27
16,dos Ipes,Avenida,Jardim Horizonte Azul,Belo Horizonte,31849968,Casa,346000.0,2015-02-22
...,...,...,...,...,...,...,...,...
1436,Flor do Campo,Avenida,Vila Horizonte,Sao Paulo,4868406,Sala Comercial,540000.0,2018-02-09
1481,Ribeirao Claro Norte,Rua,Vila Primavera,Sao Paulo,4841355,Casa,447000.0,2016-05-12
1486,Porto das Flores,Avenida,Vila Primavera,Sao Paulo,5813031,Kitnet,222000.0,2018-10-12
1489,Capitao Noronha,Rua,Vila Primavera,Sao Paulo,2712517,Kitnet,245000.0,2022-04-07
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [42]:
# Exiba os imóveis da cidade "Curitiba" cujo bairro não seja "Residencial Tingui".
# aqui fiz  sem variável . 

df[(df["cidade"] == "Curitiba") & (df["bairro"] != "Residencial Tingui")]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [ ]:
# Exiba os imóveis da cidade "Curitiba" cujo bairro não seja "Residencial Tingui".
# aqui fiz com variável. 

df_curitiba = df[df["cidade"] == "Curitiba"]

df_curitiba = df_curitiba[df_curitiba["bairro"] != "Residencial Tingui"]

df_curitiba

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [47]:
# Exiba os imóveis da cidade "Curitiba" cujo bairro não seja "Residencial Tingui".
# aqui fiz com variável também 

df_filtrado = df[(df["cidade"] == "Curitiba") & (df["bairro"] != "Residencial Tingui")]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

In [ ]:
# Exiba os imóveis cujo valor seja maior que a média geral e cuja data de aquisição seja anterior a 2021-01-01.
# Criando duas  variáveis . 

df_valor_medio =  df["valor"].mean()

df_filtrado = df[(df_valor_medio < df["valor"]) & (df["data_aquisicao"] < "2021-01-01")]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
17,Antonio Loureiro,Rua,Jardim Horizonte Azul,Belo Horizonte,31840545,Galpao,2490000.0,2015-05-05
...,...,...,...,...,...,...,...,...
1480,Flor do Campo Central,Rua,Vila Primavera,Sao Paulo,2889729,Casa,1082500.0,2016-02-08
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1484,Helena Sampaio Oeste,Avenida,Vila Primavera,Sao Paulo,2557295,Casa,1345000.0,2017-07-02
1487,das Mangueiras,Largo,Vila Primavera,Sao Paulo,4122666,Sobrado,1407500.0,2020-10-01
1488,Raul Peixoto Norte,Rua,Vila Primavera,Sao Paulo,4063339,Casa,1127500.0,2020-10-17

In [59]:
# Exiba os imóveis cujo valor seja maior que a média geral e cuja data de aquisição seja anterior a 2021-01-01.
# Criando duas  variáveis . 

df_valor_medio =  df["valor"].mean()

df_filtrado = df[( df["valor"]> df_valor_medio) & (df["data_aquisicao"] < "2021-01-01")]

df_filtrado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
17,Antonio Loureiro,Rua,Jardim Horizonte Azul,Belo Horizonte,31840545,Galpao,2490000.0,2015-05-05
...,...,...,...,...,...,...,...,...
1480,Flor do Campo Central,Rua,Vila Primavera,Sao Paulo,2889729,Casa,1082500.0,2016-02-08
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1484,Helena Sampaio Oeste,Avenida,Vila Primavera,Sao Paulo,2557295,Casa,1345000.0,2017-07-02
1487,das Mangueiras,Largo,Vila Primavera,Sao Paulo,4122666,Sobrado,1407500.0,2020-10-01
1488,Raul Peixoto Norte,Rua,Vila Primavera,Sao Paulo,4063339,Casa,1127500.0,2020-10-17

In [62]:
# esse comando me mostra o tamanho que cada coluna ocupa , por exemplo, o logradouro ocupa 94 mil bytes que é igual 94 kb

df.memory_usage (deep=True)

Index                 132
logradouro          94765
tipo_logradouro     80850
bairro             100437
cidade              89014
cep                 12000
tipo                85015
valor               12000
data_aquisicao      12000
dtype: int64

In [63]:
# Se você quiser o total de memória do DataFrame inteiro (em vez de coluna por coluna), pode somar tudo:

df.memory_usage (deep=True).sum()

np.int64(486213)

In [71]:
# Exiba os imóveis cujo CEP comece com "80" e cujo tipo seja "casa".
# astype transforma a coluna cep em string e precisa transformar para string porque o startswith só 
# funciona com string , para pegar algo que começa com  só string, não da pra fazer com número.
# usei uma variável só , mas  da pra fazer até sem variável 
# lembrando que toda vez antes de usar o startwith  tem que ter .str  antes conforme abaixo. 

df_imovel_especifico = df[(df["cep"].astype(str).str.startswith("80")) & (df["tipo"] == "Casa")]

df_imovel_especifico

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
257,das Figueiras,Viela,Alto Capivari,Curitiba,80335358,Casa,586000.0,2017-02-22
268,Laranjeiras,Alameda,Bairro das Industrias,Curitiba,80304204,Casa,630000.0,2014-01-08
270,Flor do Campo Norte,Avenida,Bairro das Industrias,Curitiba,80648893,Casa,617500.0,2017-08-24
276,Alto do Cedro Sul,Rua,Bairro das Industrias,Curitiba,80198256,Casa,1082500.0,2023-07-11
294,Augusto Ferraz Sul,Rodovia,Jardim Araucaria,Curitiba,80412787,Casa,460000.0,2016-03-09
295,Canario Branco,Alameda,Jardim Araucaria,Curitiba,80239212,Casa,655000.0,2016-10-20
304,das Violetas,Rua,Jardim Araucaria,Curitiba,80986490,Casa,705000.0,2026-02-18
312,Monte Claro,Rodovia,Jardim das Estacoes,Curitiba,80930040,Casa,712500.0,2018-07-09
323,Clara Nogueira,Avenida,Jardim das Estacoes,Curitiba,80579738,Casa,1385000.0,2026-02-19
345,Augusto Ferraz Sul,Alameda,Vila Neve Branca,Curitiba,80501872,Casa,311000.0,2014-09-04
359,das Orquideas,Rua,Vila Pinheiros,Curitiba,80576763,Casa,1037500.0,2018-07-01
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04

In [72]:
# Exiba os imóveis cujo CEP comece com "80" e cujo tipo seja "casa".
# astype transforma a coluna cep em string e precisa transformar para string porque o startswith só 
# funciona com string , para pegar algo que começa com  só string, não da pra fazer com número.
# aqui usei duas variáveis 
# lembrando que toda vez antes de usar o startwith  tem que ter .str  antes conforme abaixo. 

df_cep_tratado= df[df["cep"].astype(str).str.startswith("80")]

df_imovel_tratado = df_cep_tratado[df_cep_tratado["tipo"]=="Casa"]

df_imovel_tratado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
257,das Figueiras,Viela,Alto Capivari,Curitiba,80335358,Casa,586000.0,2017-02-22
268,Laranjeiras,Alameda,Bairro das Industrias,Curitiba,80304204,Casa,630000.0,2014-01-08
270,Flor do Campo Norte,Avenida,Bairro das Industrias,Curitiba,80648893,Casa,617500.0,2017-08-24
276,Alto do Cedro Sul,Rua,Bairro das Industrias,Curitiba,80198256,Casa,1082500.0,2023-07-11
294,Augusto Ferraz Sul,Rodovia,Jardim Araucaria,Curitiba,80412787,Casa,460000.0,2016-03-09
295,Canario Branco,Alameda,Jardim Araucaria,Curitiba,80239212,Casa,655000.0,2016-10-20
304,das Violetas,Rua,Jardim Araucaria,Curitiba,80986490,Casa,705000.0,2026-02-18
312,Monte Claro,Rodovia,Jardim das Estacoes,Curitiba,80930040,Casa,712500.0,2018-07-09
323,Clara Nogueira,Avenida,Jardim das Estacoes,Curitiba,80579738,Casa,1385000.0,2026-02-19
345,Augusto Ferraz Sul,Alameda,Vila Neve Branca,Curitiba,80501872,Casa,311000.0,2014-09-04
359,das Orquideas,Rua,Vila Pinheiros,Curitiba,80576763,Casa,1037500.0,2018-07-01
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04

In [73]:
# Exiba o apartamento mais caro da cidade "Belo Horizonte"
# lembrando que o sort_values sempre vem do menor para o maior, caso queira do maior para o menor,
# tem que ser sort_values (nome da coluna de ordenação , ascending=False ) , 
#  , precisa usar o False , ai vem do maior para o menor. 
# do menor para o maior  pode ser df.sort_values("valor", ascending=True)  ou df.sort_values("valor") 

df_imovel_tratado = df[df["cidade"] == "Belo Horizonte"]

df_imovel_tratado = df_imovel_tratado[df_imovel_tratado["tipo"] == "Apartamento"].sort_values("valor", ascending=False)

df_imovel_tratado

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
43,Olivia Monteiro Norte,Avenida,Jardim Serra Clara,Belo Horizonte,30645914,Apartamento,1077500.0,2023-11-12
11,Clara Nogueira,Rua,Alto da Pedreira,Belo Horizonte,30333799,Apartamento,1030000.0,2024-10-15
142,Veredas do Lago,Avenida,Vila Ouro Preto Nova,Belo Horizonte,30771689,Apartamento,965000.0,2020-11-16
13,Vale Verde,Rua,Alto da Pedreira,Belo Horizonte,31460215,Apartamento,947500.0,2026-03-07
69,Laranjeiras,Avenida,Residencial Pampulha Sul,Belo Horizonte,30574597,Apartamento,915000.0,2016-10-24
42,Alto do Cedro,Estrada,Jardim Serra Clara,Belo Horizonte,30174048,Apartamento,810000.0,2021-07-29
131,Dona Celina Sul,Praca,Vila Mineira,Belo Horizonte,31507953,Apartamento,795000.0,2024-09-12
139,das Violetas Sul,Avenida,Vila Ouro Preto Nova,Belo Horizonte,31331296,Apartamento,772500.0,2018-11-26
64,Boa Esperanca,Rua,Parque das Mangueiras,Belo Horizonte,30886138,Apartamento,732500.0,2025-12-08
76,Nova Aurora,Avenida,Residencial Pampulha Sul,Belo Horizonte,31823113,Apartamento,700000.0,2023-08-18
48,Engenheiro Tavares,Avenida,Parque das Mangueiras,Belo Horizonte,31068428,Apartamento,682500.0,2015-12-09
22,Sao Gabriel,Avenida,Jardim Horizonte Azul,Belo Horizonte,31365999,Apartamento,665000.0,2022-03-23
36,Engenheiro Tavares,Praca,Jardim Serra Clara,Belo Horizonte,31720103,Apartamento,652500.0,2017-06-05
30,Vista Alegre,Praca,Jardim Horizonte Azul,Belo Horizonte,31223067,Apartamento,652500.0,2026-04-01
112,Canario Branco,Praca,Vila Esperanca Norte,Belo Horizonte,31929395,Apartamento,627500.0,2025-09-02
85,Boa Esperanca,Rua,Santa Leonor,Belo Horizonte,30685232,Apartamento,600000.0,2018-09-09
24,Padre Avelino,Avenida,Jardim Horizonte Azul,Belo Horizonte,30898169,Apartamento,558000.0,2023-10-09
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
129,Vale Verde,Praca,Vila Mineira,Belo Horizonte,30390044,Apartamento,523000.0,2022-08-16
89,dos Ipes,Travessa,Santa Leonor,Belo Horizonte,31124545,Apartamento,506000.0,2019-08-11
141,das Violetas,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30591839,Apartamento,498000.0,2020-09-27
115,Porto das Flores Oeste,Rua,Vila Mineira,Belo Horizonte,30968503,Apartamento,489000.0,2015-04-13
60,Clara Nogueira,Avenida,Parque das Mangueiras,Belo Horizonte,31868719,Apartamento,476000.0,2024-03-01
23,Horizonte Azul,Avenida,Jardim Horizonte Azul,Belo Horizonte,30327391,Apartamento,466000.0,2023-04-13
55,Olivia Monteiro Central,Avenida,Parque das Mangueiras,Belo Horizonte,31520844,Apartamento,455000.0,2018-03-01
66,das Cerejeiras,Rua,Residencial Pampulha Sul,Belo Horizonte,30513806,Apartamento,449000.0,2014-02-02
53,Vale Verde,Rua,Parque das Mangueiras,Belo Horizonte,30444531,Apartamento,442000.0,2017-10-23
68,Raul Peixoto,Rua,Residencial Pampulha Sul,Belo Horizonte,30458611,Apartamento,427000.0,2016-09-08
72,Alto do Cedro,Rua,Residencial Pampulha Sul,Belo Horizonte,30092961,Apartamento,415000.0,2017-11-07
71,Primavera Sul,Rua,Residencial Pampulha Sul,Belo Horizonte,31520137,Apartamento,409000.0,2017-07-16
34,das Cerejeiras,Rua,Jardim Serra Clara,Belo Horizonte,31143618,Apartamento,407000.0,2016-08-05
49,das Violetas,Rua,Parque das Mangueiras,Belo Horizonte,31286171,Apartamento,400000.0,2016-02-08
96,Monte Claro,Rua,Santa Leonor,Belo Horizonte,31746571,Apartamento,399000.0,2023-09-26
114,Santa Cecilia,Rua,Vila Mineira,Belo Horizonte,30609448,Apartamento,394000.0,2014-04-25
103,Sao Vicente,Avenida,Vila Esperanca Norte,Belo Horizonte,31994522,Apartamento,366000.0,2016-06-21
106,Benedito Campos,Avenida,Vila Esperanca Norte,Belo Horizonte,30642059,Apartamento,365000.0,2018-10-04
134,dos Ipes,Travessa,Vila Mineira,Belo Horizonte,31350437,Apartamento,320000.0,2025-11-07
116,Dona Celina,Praca,Vila Mineira,Belo Horizonte,31142138,Apartamento,309000.0,2016-03-29
127,Paineiras,Rua,Vila Mineira,Belo Horizonte,31930506,Apartamento,302000.0,2021-07-12
110,Campo Sereno,Avenida,Vila Esperanca Norte,Belo Horizonte,31791478,Apartamento,295000.0,2023-10-05
132,Sol Nascente,Rua,Vila Mineira,Belo Horizonte,30824568,Apartamento,295000.0,2024-12-27
31,Engenheiro Tavares,Rua,Jardim Serra Clara,Belo Horizonte,30851933,Apartamento,276000.0,2015-05-14
46,das Mangueiras,Avenida,Parque das Mangueiras,Belo Horizonte,31410786,Apartamento,271000.0,2014-12-26
14,Veredas do Lago,Avenida,Jardim Horizonte Azul,Belo Horizonte,30457770,Apartamento,256000.0,2014-09-24
83,dos Jacarandas,Rodovia,Santa Leonor,Belo Horizonte,30430973,Apartamento,253000.0,2017-03-09
51,das Orquideas Leste,Rua,Parque das Mangueiras,Belo Horizonte,30521517,Apartamento,239000.0,2016-12-23

In [ ]:
# Exiba o apartamento mais caro da cidade "Belo Horizonte"
# aqui  é uma série ,  então como não é um DF dentro do sort values  não tem a coluna valor diferente  do notebook anterior. 

df_bh = df[(df["cidade"] == "Belo Horizonte") & (df["tipo"] == "Apartamento")]["valor"].sort_values(ascending=False)

df_bh

43     1077500.0
11     1030000.0
142     965000.0
13      947500.0
69      915000.0
42      810000.0
131     795000.0
139     772500.0
64      732500.0
76      700000.0
48      682500.0
22      665000.0
36      652500.0
30      652500.0
112     627500.0
85      600000.0
24      558000.0
9       527000.0
129     523000.0
89      506000.0
141     498000.0
115     489000.0
60      476000.0
23      466000.0
55      455000.0
66      449000.0
53      442000.0
68      427000.0
72      415000.0
71      409000.0
34      407000.0
49      400000.0
96      399000.0
114     394000.0
103     366000.0
106     365000.0
134     320000.0
116     309000.0
127     302000.0
110     295000.0
132     295000.0
31      276000.0
46      271000.0
14      256000.0
83      253000.0
51      239000.0
Name: valor, dtype: float64

In [ ]:
# Mostre a quantidade de imóveis cadastrados em cada cidade.
# nesse caso  , o necessário  é usar o size para fazer a contagem Conforme  no próximo exemplo
# se usamos o count  não fica bom porque ele conta todas as colunas . 
# outra coisa , contar linha que é o que ele faz aqui não precisa escolher coluna no size que é o que
# conta. 
# aqui fiz sem variável . 


df.groupby("cidade").size()

In [ ]:
# Mostre a quantidade de imóveis cadastrados em cada cidade.
# assim não é legal porque ele mostra todas as colunas  com as mesmas contagens, nesse o melhor é usar o size()
# outra coisa , contar linha que é o que ele faz aqui não precisa escolher coluna no count que é o que
# conta. 
# aqui fiz sem variável . 


df.groupby("cidade").count()

In [ ]:
# Mostre a quantidade de imóveis cadastrados em cada cidade.
# perguntar para o professor Lucas se pode ser assim também ao invés do groupby 
# aqui eu já escolho a coluna,  para contar linhas , por isso o ideal é usar o primeiro exemplo com 
# size  desse exercicio. 
# aqui fiz sem variável . 


df["cidade"].value_counts()

In [ ]:
# Mostre a soma do valor dos imóveis cadastrados em cada cidade.
# aqui fiz sem variável . 

df.groupby("cidade")["valor"].sum()

In [ ]:
# Mostre o valor do imóvel mais caro de cada bairro da cidade 'Curitiba'.
# aqui eu criei uma variável só 


df_imoveis_curitiba = df[df['cidade'] == "Curitiba"]

df_imoveis_curitiba = df_imoveis_curitiba.groupby("bairro")["valor"].max()

df_imoveis_curitiba

In [ ]:
# Mostre o valor do imóvel mais caro de cada bairro da cidade 'Curitiba'.
# aqui virou um DF com uma coluna porque usei o . to_frame()


df_imoveis_curitiba = df[df["cidade"] == "Curitiba"]

df_imoveis_curitiba = df_imoveis_curitiba.groupby("bairro")["valor"].max().to_frame()

df_imoveis_curitiba

In [ ]:
# Mostre o valor do imóvel mais caro de cada bairro da cidade 'Curitiba'.
# aqui virou um DF com uma coluna porque usei o . to_frame()
#  e aqui ainda usei o .reset_index()  para separa o DF em duas colunas 

df_curitiba = df[df["cidade"]=="Curitiba"]

df_curitiba = df_curitiba.groupby("bairro")["valor"].max().to_frame().reset_index()

df_curitiba

In [ ]:
# O type ele mostra qual é o tipo de uma variável , de um objeto . 
# note que no último  que foi o que eu filtrei no exercicio acima,  ele não é um DF e sim uma serie. 

print(type(df))
print(type(df_curitiba))
print(type(df["valor"]))

In [ ]:
# Mostre o valor do imóvel mais barato de cada bairro da cidade 'Curitiba'.

df_curitiba = df[df["cidade"] == "Curitiba"]

df_curitiba = df_curitiba.groupby("bairro")["valor"].min()

df_curitiba

In [ ]:
# Liste o valor médio dos imóveis de cada tipo.

df_valor_medio = df.groupby("tipo")["valor"].mean()

df_valor_medio

In [ ]:
# Liste o valor médio dos imóveis de cada tipo.
# nesse caso aparece sem notação cientifica 

df_valor_medio = df.groupby("tipo")["valor"].mean().round()

df_valor_medio

In [ ]:
# Liste o valor médio dos imóveis de cada tipo, apenas para os imóveis da cidade de 'Sao Paulo'.

df_sao_paulo = df[df["cidade"] == "Sao Paulo"]

df_sao_paulo =  df_sao_paulo.groupby("tipo")["valor"].mean().round()

df_sao_paulo

In [ ]:
# Liste o valor médio dos imóveis de cada tipo.
# nesse caso aparece sem notação cientifica 
# o round tira a notação cientifica 


df_valor_medio_sp = df[df["cidade"] == "Sao Paulo"]

df_valor_medio_sp =  df_valor_medio_sp.groupby("tipo")["valor"].mean().round()

df_valor_medio_sp

In [ ]:
# Mostre a soma total dos valores dos imóveis em cada cidade, ordenando do maior para o menor valor total.
# aqui porque eu não tive que colocar  .sort_values("valor" , ascending=False)  ? Porque é uma série, e como é serie  não posso colocar uma coluna dentro do sort_values

df_valormax_cidade = df.groupby("cidade")["valor"].sum().sort_values(ascending = False)

df_valormax_cidade

In [ ]:
# Mostre a soma total dos valores dos imóveis em cada cidade, ordenando do maior para o menor valor total.
# sort_values(ascending=False) mostra a ordenação decrescente 
# sort_values  mostra a ordenação crescente 
# aqui ele está usando por debaixo dos panos no Pandas metplotlib uma vez que eu tenho ela instalada o python deixa.
# aqui eu baixei em Excel  para testar ,  a linha do código que baixa em excel  to_excel tem que vir abaixo da linha que cria o cálculo, esse é  um ponto importante.
#  Outra coisa importante é que com esse código o gráfico só é gerado no python, para exportar para o Excel não serve. 
# se eu quiser usar o gráfico de coluna em pé,  é  .plot.bar()  se for coluna deitado é .plot.barh()


df_valormax_cidade = df.groupby("cidade")["valor"].sum().sort_values(ascending=False)

df_valormax_cidade.plot.bar()

df_valormax_cidade.to_excel("resultado.xlsx")

In [ ]:
# Mostre a soma total dos valores dos imóveis em cada cidade, ordenando do maior para o menor valor total 
# aqui ele está usando por debaixo dos panos no Pandas metplot uma vez que eu tenho ela instalada o python deixa.

df_valormax_cidade = df.groupby("cidade")["valor"].sum().sort_values(ascending = False)

df_valormax_cidade.plot.barh()

In [ ]:
# Mostre a soma total dos valores dos imóveis em cada cidade, ordenando do maior para o menor valor total.
# esse .pie() mostra o gráfico de pizza usando o matplotlib no pandas . 

df_valormax_cidade = df.groupby("cidade")["valor"].sum().sort_values(ascending = False)

df_valormax_cidade.plot.pie()

In [ ]:
# A imobiliária deseja avaliar o estoque de alto padrão em Porto Alegre. 
# Calcule o valor total dos imóveis de cada tipo, considerando apenas imóveis com valor acima de 900000 adquiridos após 2022.
# note que aqui eu tive que fazer os filtros e depois agrupei ,  se eu não tivesse agrupado ele traria um DF  mas como eu agrupei ele trouxe uma série. 

df_portoalegre_altopadrao = df[(df["cidade"] == "Porto Alegre") & (df["valor"]> 900000) & (df["data_aquisicao"] > "2022-12-31")]

df_portoalegre_altopadrao = df_portoalegre_altopadrao.groupby("tipo")["valor"].sum()

df_portoalegre_altopadrao

In [ ]:
# A imobiliária quer avaliar quais tipos de imóveis possuem maior valor financeiro no estoque. 
# Calcule a soma do valor dos imóveis de cada tipo, considerando apenas imóveis adquiridos em 2025 e com valor acima de 1000000. 
# Ordene do maior valor total para o menor.

df_estoque_maior_valor = df[(df["data_aquisicao"] >= "2025-01-01") & (df["data_aquisicao"] <= "2025-12-31") & (df["valor"] > 1000000)]

df_estoque_maior_valor = df_estoque_maior_valor.groupby("tipo")["valor"].sum().sort_values(ascending = False)

df_estoque_maior_valor

In [ ]:
# Para avaliar oportunidades de revenda em São Paulo, 
# exiba a quantidade de imóveis em cada bairro, considerando apenas apartamentos com valor abaixo de 500000 e adquiridos antes de 2021
# aqui não tem resultado 

df_revenda_sp = df[(df["cidade"]=="Sao Paulo") & (df["tipo"]=="Apartamento") & (df["valor"] < 500000) & (df ["data_aquisicao"] < "2021-01-01")]

df_revenda_sp = df_revenda_sp.groupby("bairro").size()

In [ ]:
# Para identificar os bairros com maior oferta de imóveis acessíveis, mostre a quantidade de imóveis cadastrados em cada bairro, 
# considerando apenas aqueles com valor abaixo de 250000. Exiba somente os bairros que possuem pelo menos 3 imóveis.
# note que aqui eu usei um filtro na série e mesmo assim filtro , não entendi muito bem porque filtro a coluna de contagem e não de nome de bairro mas filtro rs . 


df_maiores_ofertas = df[df["valor"] < 250000]

df_maiores_ofertas = df_maiores_ofertas.groupby("bairro").size()

df_maiores_ofertas = df_maiores_ofertas[df_maiores_ofertas >=3]

df_maiores_ofertas

In [ ]:
#A imobiliária quer avaliar quais tipos de imóveis possuem maior valor financeiro no estoque. Calcule a soma do valor dos imóveis de cada tipo, 
# considerando apenas imóveis adquiridos em 2025 e com valor acima de R$ 1 Milhão. Ordene do maior valor total para o menor.

df_maior_valor_tipo = df[(df["data_aquisicao"] >= "2025-01-01") & (df["data_aquisicao"] <= "2025-12-31") &  (df["valor"] > 1000000)]

df_maior_valor_tipo = df_maior_valor_tipo.groupby("tipo")["valor"].sum().sort_values(ascending=False)

df_maior_valor_tipo

In [ ]:
# Para avaliar oportunidades de revenda em São Paulo, exiba a quantidade de imóveis em cada bairro, 
# considerando apenas apartamentos com valor abaixo de 400000 e adquiridos antes de 2021

df_revenda_saopaulo = df[(df["cidade"] == "Sao Paulo")&(df["tipo"] == "Apartamento") & (df["valor"] < 400000) & (df["data_aquisicao"] < "2021-01-01")]

df_revenda_saopaulo = df_revenda_saopaulo.groupby("bairro").size()

df_revenda_saopaulo

In [ ]:
# Para identificar os bairros com maior oferta de imóveis acessíveis, mostre a quantidade de imóveis cadastrados em cada bairro, 
# considerando apenas aqueles com valor abaixo de 250000. Exiba somente os bairros que possuem pelo menos 3 imóveis.

df_imoveis_por_bairros = df[df["valor"] < 250000]

df_imoveis_por_bairros = df_imoveis_por_bairros.groupby("bairro").size()

df_imoveis_por_bairros = df_imoveis_por_bairros[df_imoveis_por_bairros >=3]

df_imoveis_por_bairros

In [ ]:
# A imobiliária quer saber quais bairros de Belo Horizonte possuem maior volume financeiro em imóveis residenciais. 
# Calcule o valor total dos imóveis de cada bairro, considerando apenas casas, apartamentos e sobrados adquiridos após 2021. (Ordenados do maior valor para o menor)
# repare que aqui eu tenho que usar no filtro  o & e o | que é o or . Tenho que por também entre 2 parentêses para não bagunçara lógica. 

df_bh_bairros_maiores_valores = df[(df["cidade"]== "Belo Horizonte") & ((df["tipo"] == "Casa") | (df["tipo"] == "Apartamento") | (df["tipo"] == "Sobrado")) & (df["data_aquisicao"] > "2021-12-31")]

df_bh_bairros_maiores_valores = df_bh_bairros_maiores_valores.groupby("bairro")["valor"].sum().sort_values(ascending = False)

df_bh_bairros_maiores_valores

In [ ]:
# Exiba um gráfico de pizza (pie) do valor total dos imóveis por tipo.
# não tem ()  no  plot porque o plot é um acesso a biblioteca matplotlib , o que é a função é o pie.

df_total_tipo = df.groupby("tipo")["valor"].sum()

df_total_tipo.plot.pie()

In [ ]:
# Exiba um gráfico de barras horizontal (barh) do valor total dos imóveis de cada  bairro da cidade "Sao Paulo".
# note que a soma  sempre vem depois do filtro conforme abaixo. 
#  aqui eu não posso fazer assim df_sp = df[(df["cidade"] == "Sao Paulo") & (df.groupby("bairro")["valor"].sum())]  porque o & só junta dois filtros 
# e não  um f iltro com o groupby.  Se eu quiser  fazer em uma linha só, ficaria assim : 
# df_sp = df[(df["cidade"] == "Sao Paulo")].groupby("bairro")["valor"].sum().sort_values(ascending=False)


df_sp = df[(df["cidade"] == "Sao Paulo")]

df_sp = df_sp.groupby("bairro")["valor"].sum().sort_values(ascending=False)

df_sp.plot.barh()

In [ ]:
# Mude o tipo da coluna "data_aquisicao" para datetime. Use pd.to_datetime
# dtype('<M8[us]')  esse resultado quer  dizer  que a coluna data_aquissicao  já é data 

df["data_aquisicao"].dtype

In [ ]:
# Mude o tipo da coluna "data_aquisicao" para datetime. Use pd.to_datetime
# criei variável mas poderia fazer direto sem variável também , a depender do que eu quero . 
# e o comando para mudar o tipo da data   para data mesmo caso  não seja é chamar o pandas  com pd    depois  . to_datetime     
#como o datatime  é uma função tem que por entre ()  mas  entre []  pra mostrar a coluna que quero mudar .   ai fica  pd.to_datetime(df["data_aquisicao"])


df_data_alterada = pd.to_datetime(df["data_aquisicao"])

df_data_alterada

#df_data_alterada.dtype

In [ ]:
# Crie as colunas ano e mes. Utilize df.data_aquisicao.dt.year e df.data_aquisicao.dt.month.
# vamos lá , a primeira informação importante aqui é que o dt é um comando que extrai partes de uma data de uma coluna no DF . Ele é como o  astype(str).str.startswith
#  mas ao invés de texto pega a data .  
# outra informação aqui é que o enunciado pede para criar colunas no DF,  logo  a variável que eu crio tem que ser uma variável com o nome das  coluans que quero criar
# entre []  e com ""  conforme abaixo . 
#  esse exericio até da pra fazer sem variável também  mas  não faz sentido  porque provavelmente vou querer guardar essas duas colunas que coloquei . 
# uma coisa que achei estranho é que aqui  eu coloquei duas colunas no DF original ,  não teria que ser um novo DF ? 
# aqui o ano é um número assim como  o mês. 

df["ano"] = df["data_aquisicao"].dt.year
df["mes"]= df["data_aquisicao"].dt.month

df

In [ ]:
# Exiba um gráfico de linhas com a evolução do valor total dos imóveis agrupados por ano.
#  veja que como o exercicio pede o gráfico por linha ,  eu  vou usar a função line() e de novo com o acessador plot. 
# aqui eu não ordenei porque ele já vem ordenado pelo ano  por conta do groupby , o groupby sempre ordena pelo índice.

df_valor_ano = df.groupby("ano")["valor"].sum()

df_valor_ano.plot.line()

In [ ]:
# Exiba um gráfico de barras com a quantidade de imóveis adquiridos em cada ano.

df_qtd_imóveis_ano = df.groupby("ano").size()

df_qtd_imóveis_ano.plot.bar()

In [ ]:
# Faça um gráfico de linhas que mostre a evolução do valor dos imóveis adquiridos no ano de 2020, ao longo dos meses.

imoveis_evolucao_2020 = df[(df["data_aquisicao"] >= "2020-01-01") & (df["data_aquisicao"] <= "2020-12-31")].groupby("mes")["valor"].sum()

imoveis_evolucao_2020.plot.line()

In [ ]:
#  ou 

# Faça um gráfico de linhas que mostre a evolução do valor dos imóveis adquiridos no ano de 2020, ao longo dos meses.
# note que  aqui o ano  é um número e não tem que por entre ""

imoveis_evolucao_2020 = df[df["ano"]== 2020].groupby("mes")["valor"].sum()

imoveis_evolucao_2020.plot.line()

In [ ]:
#Calcule o valor total dos imóveis por ano, considerando apenas casas, apartamentos e sobrados adquiridos. 
# Exiba um gráfico de barras agrupado por ano e tipo de imóvel.
# note que aqui não precisei usar o sort_values  ano  porque no groupby  ele já meio que ordena por ano também .
# note 

total_imoveis_ano = df[(df["tipo"] == "Casa") | (df["tipo"] == "Apartamento") | (df["tipo"] == "Sobrado")]

total_imoveis_ano = total_imoveis_ano.groupby(["ano","tipo"])["valor"].sum().unstack()

total_imoveis_ano

total_imoveis_ano.plot.bar()

In [ ]:
# Exiba em um gráfico a média de valores dos apartamentos da cidade "Belo Horizonte", de cada ano.
# aqui usei o line porque é bom pra ver o comportamento (evolução) da média nos anos . 

valormedio_bh = df[(df["cidade"] == "Belo Horizonte") & (df["tipo"] == "Apartamento")]

valormedio_bh = valormedio_bh.groupby("ano")["valor"].mean()

valormedio_bh.plot.line()